spring:
  datasource:
    url: jdbc:h2:mem:parametrizationdb;DATABASE_TO_UPPER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.H2Dialect

  cache:
    type: redis  # Aqui estamos definindo Redis como o mecanismo de cache padrão

  redis:
    host: localhost
    port: 6379
    # Se precisar usar senha no Redis, descomente a linha abaixo
    # password: my_redis_password
    time-to-live: 600000 # 10 minutos de TTL para os caches armazenados no Redis
